### ISSUE TITLE
support for dark status bar icons

### ISSUE THREAD

**Issue by aaalvaro** [mank319/elementaryPlus#442] opened 2017-05-20 23:58 UTC
Hi! I really appreciate your work on the icons.
However it seems that no attention is being paid to the dark variant of icons. On elementary, when your desktop image is a light color and not too messy, the Wingpanel stays transparent and its icons and text become dark.
Example below:
![screenshot from 2017-05-20 20 57 13](https://cloud.githubusercontent.com/assets/25199540/26280150/05100ba6-3d9f-11e7-81a5-1cd75bf00d56.png)

That makes them unusable =\

**Comment by bil-elmoussaoui** [comment] 2017-05-21 00:03
It's impossible to do that by using elementaryPlus, elementary uses symbolic icons (SVG ones, that can be styled using CSS) but those icons supported by elementaryPlus (hardcoded by devs to be pngs or svg) cannot be themed the same way elementary icons are.

**Comment by quassy** [comment] 2017-06-28 16:59
Duplicate of #416. Thanks for your report nontheless. 

Unfortunately I believe @bil-elmoussaoui is correct, at least from everything I have heard so far.

**Closed by quassy** 2017-06-28 16:59 UTC
Labels: duplicate
