### ISSUE TITLE
libreoffice 5 icons are missing while installing using .deb

### ISSUE THREAD

**Issue by sandeepbhardwaj** [mank319/elementaryPlus#336] opened 2016-01-08 07:10 UTC
Install libreoffice 5 with deb package then it's not picking the elementary plus icons. I have also verified in usr/share/applications location there is no .desktop file for libreoffice created in this case.

Note:- when installing libreoffice using ppa its picking the icons.

**Comment by elmat0** [comment] 2016-01-09 02:26
Is there a .desktop file in `~/.local/share/applications/` instead?

**Comment by sandeepbhardwaj** [comment] 2016-01-09 05:55
No,  there is no ```.desktop``` file for libreOffice inside ```~/.local/share/applications/```

**Comment by sandeepbhardwaj** [comment] 2016-01-09 05:56
No, there is no ```.desktop``` file for libreOffice inside ```~/.local/share/applications/```

**Comment by sandeepbhardwaj** [comment] 2016-01-09 05:59
No, there is no ```.desktop``` file for libreOffice inside ```~/.local/share/applications/```

**Comment by bil-elmoussaoui** [comment] 2016-01-12 12:55
@sandeepbhardwaj and in `/usr/share/applications`? `/usr/local/share/applications`?

**Comment by sandeepbhardwaj** [comment] 2016-01-12 15:00
Yes these are under ```/usr/local/share/applications/``` location

**Comment by cybre** [comment] 2016-01-13 01:04
@sandeepbhardwaj Can you post the output of `cat /usr/local/share/applications/*libre* | grep Icon`, please?

**Comment by elmat0** [comment] 2016-01-13 06:14
Just noticed [this](https://github.com/mank319/elementaryPlus/issues/297) duplicate bug.

**Comment by quassy** [comment] 2016-01-15 03:11
Duplicate of #297, please continue posting there.

**Closed by quassy** 2016-01-15 03:11 UTC
