### ISSUE TITLE
Icon request: Google Chrome

### ISSUE THREAD

**Issue by png2378** [mank319/elementaryPlus#314] opened 2015-10-14 14:22 UTC
After upgrading to version 46.0.2490.71 Chrome got icon in "material design" style. 

![New Icon](http://my-chrome.ru/wp-content/uploads/2015/08/product_logo_name_48-e1438443127879.png)

It does not fit into the overall style.

**Comment by quassy** [comment] 2015-10-14 15:19
Duplicate of #30

**Closed by quassy** 2015-10-14 15:19 UTC
