### ISSUE TITLE
elementary+ Configurator not present in Slingshot immediately after installing/updating

### ISSUE THREAD

**Issue by harshi3t** [mank319/elementaryPlus#265] opened 2015-07-13 17:53 UTC
It appears only after restarting slingshot-launcher.

**Comment by RafaelCz** [comment] 2015-07-21 17:03
@cybre perhaps adding `update-desktop-database -q` to the postinst script might solve the issue.

**Comment by cybre** [comment] 2015-07-21 23:07
@RafaelCz Done, now we wait :)

**Comment by cybre** [comment] 2015-07-21 23:26
Nope, that didn't work.

**Comment by cybre** [comment] 2015-07-22 01:16
I give up. I don't know what the problem is. The launcher shows up in search but not in the overview.

**Comment by cybre** [comment] 2015-07-22 02:28
This has been hopefully fixed in the latest version. Can you confirm?

**Comment by harshi3t** [comment] 2015-07-22 06:32
Can confirm. It's fixed :+1:

**Closed** 2015-07-22 12:36 UTC
Labels: bug, help wanted
