### ISSUE TITLE
elementaryplus-configurator does not work

### ISSUE THREAD

**Issue by SinisaPerovic** [mank319/elementaryPlus#192] opened 2015-06-24 18:21 UTC
Hi.
I'm using two computers with up to date 64bit Freya with almost same set of applications installed, but on one of them elementaryplus-configurator does not change the icons, without any errors shown in terminal. I'm trying to change HP, Skype, Mega and WizNote and using the latest elementaryplus-configurator from the PPA. On other PC everything is OK.

Can you pls tell me is there some log or any other info that I can send you to look into this?

Thank you for your apps.

Cheers,
Sinisa Perovic

**Comment by cybre** [comment] 2015-06-24 18:28
Looks like the patched sni-qt is not installed. Are you sure you've updated/upgraded your system after adding the PPA?

**Comment by RafaelCz** [comment] 2015-06-24 23:15
@SinisaPerovic  let's see what version of sni-qt is installed, please run the following command in terminal:
 `dpkg -l | grep sni-qt`

**Comment by bil-elmoussaoui** [comment] 2015-06-24 23:38
Be sure that sni-qt 32 bits version is installed too.

**Comment by SinisaPerovic** [comment] 2015-06-25 07:38
Thank you guys for your quick replies.

- yes, I did update/dist-upgrade the system after installation
- yes, I have both 32bit and 64bit sni-qt installed and both versions are 0.2.6-0ubuntu1.1

**Comment by cybre** [comment] 2015-06-25 16:24
I'm not sure, but you can try installing the patched sni-qt manually.
[sni-qt](https://launchpad.net/~cybre/+archive/ubuntu/elementaryplus/+files/sni-qt_0.2.6-0ubuntu1.1_amd64.deb)
[sni-qt:i386](https://launchpad.net/~cybre/+archive/ubuntu/elementaryplus/+files/sni-qt_0.2.6-0ubuntu1.1_i386.deb)

**Comment by SinisaPerovic** [comment] 2015-06-25 16:32
I reinstalled the both sni-qt packages and this is the situation after reboot:
- in elementaryplus-configurator all icons are OFF, has been since yesterday when I couldn't get them to work.
- Skype, HP and Mega is now working even they shouldn't because all icons are OFF in the application
- WizNote is not working

**Comment by cybre** [comment] 2015-06-25 16:48
I'll investigate the first issue.
As for WizNote, can you send me the output of `ls /tmp/sni-qt_WizNote*/icons/hicolor/16x16/apps`

**Comment by SinisaPerovic** [comment] 2015-06-25 20:53
It seems that it's regular blue icon.

![snimak zaslona s 2015-06-25 22 52 28](https://cloud.githubusercontent.com/assets/6765137/8365355/e858ddfc-1b8c-11e5-9450-ef4fe1acad5f.png)

**Comment by RafaelCz** [comment] 2015-06-25 20:58
that's strange, your wiznote has a completely different ID

**Comment by cybre** [comment] 2015-06-25 20:59
@RafaelCz Mine is the same as @SinisaPerovic's

**Comment by RafaelCz** [comment] 2015-06-25 21:09
hmm... the newest version is a few days old, they must have changed the ID. 
I'm pretty sure, I tested everything before pushing it to GitHub

**Comment by cybre** [comment] 2015-06-25 21:15
So, you've got the latest version but the icon name didn't change?

**Comment by RafaelCz** [comment] 2015-06-25 21:17
I'm not using this app, but at the time I created the icon, the ID was 212d5ac06ecac6e6fd4771c65734b922

**Comment by cybre** [comment] 2015-06-25 21:26
Well, I've installed WizNote today. If the ID changes again in the next update, we'll change how we install the WizNote icon (find the ID like in the spotify install script). I already made a pull request with the new file name so I'm going to merge it now.

**Comment by cybre** [comment] 2015-06-25 21:36
Also, I can't reproduce the bug with the icons staying on the system even after removing them via the installer so I'm going to wait a few days to see if someone else experiences the same bug, if not, I'm going to close this report. Takođe, drago mi je da neko sa naših prostora koristi elementary+ :).

**Comment by cybre** [comment] 2015-06-25 21:36
Oops.

**Comment by SinisaPerovic** [comment] 2015-06-25 21:43
@cybre Još od Jupitera i prvih Alfa Lune isključivo Elementary ;-)

**Comment by cybre** [comment] 2015-06-25 22:06
Poznajem dosta ljudi koji koriste elementary OS, više sam mislio na elementary+ (elementaryPlus) :)

**Comment by cybre** [comment] 2015-07-10 03:33
I think we fixed all of our issues with installing/removing in #230 so I'm closing this now.

**Closed by cybre** 2015-07-10 03:33 UTC
Labels: bug
