### ISSUE TITLE
Icon request - Lollypop

### ISSUE THREAD

**Issue by anaturinbor** [mank319/elementaryPlus#340] opened 2016-01-14 09:45 UTC
Lollypop is a new GNOME music playing application. https://github.com/gnumdk/lollypop

Original icon:

![6082215e-b1dc-11e5-9bb0-7ce243eb085c](https://cloud.githubusercontent.com/assets/10692755/12320959/42476a9c-bab4-11e5-9f42-ae8349b5f9a4.png)

[Desktop Entry]
Name=Lollypop
Icon=lollypop
Exec=lollypop %U
Terminal=false
Type=Application
Categories=GNOME;GTK;AudioVideo;Player;Audio;

**Comment by elmat0** [comment] 2016-01-14 15:29
@quassy was working on an icon for this [here.](https://github.com/mank319/elementaryPlus/issues/132)

**Comment by cybre** [comment] 2016-01-14 16:34
Duplicate of #132

**Closed by cybre** 2016-01-14 16:34 UTC
Labels: duplicate
